---
- name: install redis packages
  with_items: "{{ redis_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart redis

- name: enable redis service
  template:
    src: redis.j2
    dest: /etc/rc.conf.d/redis
  notify:
    - restart redis

- name: configure redis service
  template:
    src: redis.conf.j2
    dest: /usr/local/etc/redis.conf
  notify:
    - restart redis
